import FilmList from '@/components/FilmList'
import { useAppSelector } from '@/store/hooks'
import Head from 'next/head'

const FavoritePage = () => {
  const { films } = useAppSelector((state) => state.favorite)

  return (<>
    <Head>
      <title>Favorites</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <div className='container mx-auto px-5'>
      <h1 className='text-center text-3xl py-5'>Favorites</h1>
      {films.length ? <FilmList data={films} /> : <h1 className='text-3xl text-center'>Favorite list is empty</h1>}
    </div>
  </>
  )
}

export default FavoritePage
