import Head from 'next/head'
import FirstScreen from '@/sections/FirstScreen'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col min-h-[100vh]'>
        <FirstScreen />
      </main>
    </>
  )
}
