import Head from 'next/head'
import Header from '@/layout/Header'
import FirstScreen from '@/sections/FirstScreen'
import { IFilm, IFilmResult } from '@/types/interfaces'
import { GetStaticPropsResult } from 'next'

// export const getStaticProps = async () => {
//   const response = await fetch('https://www.omdbapi.com/?s=iron&page=1&apikey=dd8b229')
//   const data = await response.json()

//   return {
//     props: {
//       films: data
//     }
//   }
// }

interface IHome {
  films: IFilmResult
}

// export default function Home({films}: IHome) {
export default function Home({films}: IHome) {
  // const {Search} = films
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col min-h-[100vh]'>
        {/* <FirstScreen films={Search} /> */}
        <FirstScreen />
      </main>
    </>
  )
}
